name: CI/CD Backend Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: nouveaupass
          MYSQL_DATABASE: fullstack_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend
          npm install
          npm install cross-env --save-dev

      - name: Initialize database
        env:
          DB_HOST: localhost
          DB_USER: root
          DB_PASSWORD: nouveaupass
          DB_NAME: fullstack_db
          DB_PORT: 3306
        run: |
          cd backend
          node -e "
            const mysql = require('mysql2/promise');
            async function setupDB() {
              const connection = await mysql.createConnection({
                host: process.env.DB_HOST,
                user: process.env.DB_USER,
                password: process.env.DB_PASSWORD,
                database: process.env.DB_NAME,
                port: process.env.DB_PORT
              });
              console.log('Creating users table...');
              await connection.query(\`
                CREATE TABLE IF NOT EXISTS users (
                  id INT AUTO_INCREMENT PRIMARY KEY,
                  name VARCHAR(255) NOT NULL,
                  email VARCHAR(255) NOT NULL UNIQUE,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
              \`);
              console.log('Database initialized!');
              await connection.end();
            }
            setupDB().catch(err => {
              console.error('Database init failed:', err);
              process.exit(1);
            });
          "

      - name: Run backend tests
        env:
          DB_HOST: localhost
          DB_USER: root
          DB_PASSWORD: nouveaupass
          DB_NAME: fullstack_db
          DB_PORT: 3306
        run: |
          cd backend
          npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ismaillaa
          password: dckr_pat_sucRZsgRFqMpFUE7BxpmEvPwMKE

      - name: Build and Push Docker image
        run: |
          cd backend
          docker build -t ismaillaa/backend:latest .
          docker push ismaillaa/backend:latest
